name: JavaFX Compile and Exe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download and Unzip JavaFX
      run: |
        wget https://download2.gluonhq.com/openjfx/17.0.10/openjfx-17.0.10_linux-x64_bin-sdk.zip
        unzip openjfx-17.0.10_linux-x64_bin-sdk.zip -d javafx-sdk

    - name: Compile
      run: |
        javac --module-path javafx-sdk/javafx-sdk-17.0.10/lib --add-modules javafx.controls -d build/ src/dam/optativa/HelloWorldFx.java

    - name: Create JAR
      run: jar --create --file=build/HelloWorldFx.jar --main-class=dam.optativa.HelloWorldFx -C build/ .

    - name: Create DEB
      run: |
        jpackage --input build/ \
          --name HelloWorldFx \
          --main-jar HelloWorldFx.jar \
          --main-class dam.optativa.HelloWorldFx \
          --type deb \
          --module-path javafx-sdk/javafx-sdk-17.0.10/lib \
          --add-modules javafx.controls \


    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HelloWorldFx-Installer
        path: dist/*.deb